#!/usr/bin/env ruby --disable=gems
# frozen_string_literal: true

branch =
  if ARGV.any?
    ARGV.first
  else
    `git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/heads/ | fzf`
  end

if branch
  branch = branch.strip
end

if $? && !$?.success?
  exit $?.exitstatus
end

exec("git", "checkout", branch)
