#!/usr/bin/env ruby --disable=gems
# frozen_string_literal: true

require_relative "./git-lib"

target = resolve_target(ARGV.first)

run("git", "fu", target)

if which("git-revise")
  exec("git", "revise", "--autosquash", "#{target}~~")
else
  ENV["GIT_EDITOR"] = "true"
  exec("git", "rebase", "--interactive", "--autosquash", "#{target}~~")
end
