#!/usr/bin/env ruby --disable=gems
# frozen_string_literal: true

require_relative "./git-lib"

def ran_ok?(*command)
  _out, _err, status = popen3(*command, stdout: false, stderr: false)

  status.success?
end

if ran_ok?("git", "rev-parse", "-q", "--verify", "#{remote!}/#{default_branch}")
  exec("git", "log", "--oneline", "#{remote!}/#{default_branch}..HEAD")
else
  current_branch = run("git", "rev-parse", "--abbrev-ref", "HEAD")
  if current_branch == default_branch
    exec("git", "lg")
  else
    exec("git", "log", "--oneline", "#{default_branch}..HEAD")
  end
end
