#!/usr/bin/env ruby --disable=gems
# frozen_string_literal: true

require_relative "./git-lib"

base =
  if has_remote?(remote!)
    "#{remote!}/#{default_branch}"
  else
    default_branch
  end

exec("git", "diff", "#{base}...HEAD")
