#!/usr/bin/env bash

set -e

if git rev-parse -q --verify origin/master > /dev/null ; then
	git log --oneline origin/master..HEAD
else
	CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
	if [ $CURRENT_BRANCH == "master" ]; then
		git lg
	else
		git log --oneline master..HEAD
	fi
fi
