#!/usr/bin/env ruby --disable=gems
# frozen_string_literal: true

load File.expand_path("../git-lib", File.realpath(__FILE__))

target =
  case ARGV.first
  when /\A\d+\z/
    "HEAD~#{ARGV.first.to_i - 1}"
  when nil
    "HEAD"
  else
    ARGV.first
  end

run("git", "commit", "--fixup", target)
