#!/usr/bin/env ruby --disable=gems
# frozen_string_literal: true

load File.expand_path("../git-lib", File.realpath(__FILE__))

git_ls = run("git", "ls", say: false)
exec("git", "ri", git_ls.split("\n").size.to_s, *ARGV)
